language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - alan.tanwk@ncs.com.sg
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  - npm install -g now
  - npm update
script:
  - ng build --prod --base-href https://alantanwk.github.io/bitcoin-order-app/
  - ng lint

  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  on:
    branch: development
  after_success:
   - git push https://github.com/alantanwk/bitcoin-order-app development
   - npm audit fix
